// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCntP1g4vHLgd201EGW4rOgWQk7p9sJs3A',
    appId: '1:764953772714:web:8f5e5fb4d346b0704346d3',
    messagingSenderId: '764953772714',
    projectId: 'chatflutter-10460',
    authDomain: 'chatflutter-10460.firebaseapp.com',
    storageBucket: 'chatflutter-10460.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8NH90D6hcl5i7CNdmQqXwQ06egg9H5Po',
    appId: '1:764953772714:android:69ab167bac7ee0fa4346d3',
    messagingSenderId: '764953772714',
    projectId: 'chatflutter-10460',
    storageBucket: 'chatflutter-10460.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhbeHcJpLELAGOqiBr56aP2-8r1xH3T38',
    appId: '1:764953772714:ios:17fba8539553a2e84346d3',
    messagingSenderId: '764953772714',
    projectId: 'chatflutter-10460',
    storageBucket: 'chatflutter-10460.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhbeHcJpLELAGOqiBr56aP2-8r1xH3T38',
    appId: '1:764953772714:ios:17fba8539553a2e84346d3',
    messagingSenderId: '764953772714',
    projectId: 'chatflutter-10460',
    storageBucket: 'chatflutter-10460.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCntP1g4vHLgd201EGW4rOgWQk7p9sJs3A',
    appId: '1:764953772714:web:2b84de224ec9611c4346d3',
    messagingSenderId: '764953772714',
    projectId: 'chatflutter-10460',
    authDomain: 'chatflutter-10460.firebaseapp.com',
    storageBucket: 'chatflutter-10460.firebasestorage.app',
  );
}
